
language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    -DB_HOST=127.0.0.1
    -DB_CONNECTION=mysql_tests
    -DB_DATABASE=components_html
    -DB_USERNAME=root
    -DB_PASSWORD=

sudo: false

services:
  - mysql

before_script:
  - mysql -e 'create database components_html_tests;'

install:
  composer install

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit
  - php artisan migrate:rollback --env=testing --no-interaction -vvv

matrix:
  fast_finish: true
